version: "3"

services:
  smelly-go:
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql